### PR TITLE
South Africa Class_1 - Jarrod Benjamin - JSCore3 - Week 2

### PR DESCRIPTION
**Pull request by JarrodBen**
**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Jarrod
- Your City: South Africa
- Your Slack Name: Jarrod Benjamin

# Homework Details

- Module: JSCore3
- Week: 2

# Notes

- What did you find easy?

- What did you find hard?

- What do you still not understand?

- Any other notes?

### CODE REVIEW

**Comment by BrettScheepers** [comment]
Code looking nice and clean Jarrod nicely done

**Review by SerialCarKey — APPROVED** [review]
Hey Jarrod, super clean work on the code . you overperformed on the Dog Photo Gallery CSS

Great Job.

**Comment by aashiqabrahams123** [comment]
well done, Jarrod , easy to ready and clean code keep up the good work

**Comment by douglas86** [comment]
When rendering the image the tag isn't display only the text of the tag, In the programmer humor nothing is being rendered just a blank screen with background color

**Pull request closed without merging**
